baseURL = 'https://michaeljaniaut-dot.github.io/la.parent.these/'
languageCode = 'fr-fr'
title = 'La Parent These'
theme = 'book'

[params]
  BookTheme = 'light'
  BookToC = true
  BookSearch = true
  BookMenuBundle = '/menu'
  BookSection = '*'
  
[params.BookComments]
  enabled = false
  
[[params.ananke_socials]]
  name = 'facebook'
  url = '#'
  
[[params.ananke_socials]]
  name = 'instagram'
  url = '#'

[menu]
  [[menu.main]]
    name = 'Accueil'
    url = '/'
    weight = 1
    
  [[menu.main]]
    name = 'Prestations'
    url = '/prestations/'
    weight = 2
    
  [[menu.main]]
    name = 'Prendre RDV'
    url = '/rdv/'
    weight = 3
    
  [[menu.main]]
    name = 'Boutique'
    url = '/boutique/'
    weight = 4
    
  [[menu.main]]
    name = 'Blog'
    url = '/blog/'
    weight = 5
    
  [[menu.main]]
    name = 'Contact et FAQ'
    url = '/contact/'
    weight = 6
    
  [[menu.main]]
    name = 'A propos'
    url = '/about/'
    weight = 7
